name: Aparecium
version: '${project.version}'
main: com.ignitedev.aparecium.Aparecium
api-version: 1.19
authors: [ IgniteDEV, 2DevsStudio ]
description: "The Revealing Charm will reveal invisible ink and messages hidden by magical means.
 Simply tap a book or parchment with your wand and any hidden message will be revealed. 
 This spell is more than sufficient to overcome the basic concealing charms and so is a favourite of parents and teachers alike."
website: 2DevsStudio.com
